default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: macbookpro16
  password: 
  host: localhost

development:
  <<: *default
  database: air-quality-api-dev

test:
  <<: *default
  database: air-quality-api-test

production:
  <<: *default
  database: air-quality-api-prod
  username: macbookpro16
  password: 